various updates

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -152,22 +152,104 @@ then
   fi
 fi
 
-#backup old bin, if exists
-if [ -e $HOME/bin ]
-then
-    echo ''
-    echo "current $HOME/bin folder found!!! Creating backup..."
-    sudo mv $HOME/bin bin_old
-else
-    echo ''
-    echo "No current $HOME/bin folder found. Proceeding to link bin folder for tumx scripts..."
-fi
+echo ''
+info "starting bechelani mods"
+
+##backup old bin, if exists
+#if [ -e $HOME/bin ]
+#then
+#    echo ''
+#    echo "current $HOME/bin folder found!!! Creating backup..."
+#    sudo mv $HOME/bin bin_old
+#else
+#    echo ''
+#    echo "No current $HOME/bin folder found. Proceeding to link bin folder for tumx scripts..."
+#fi
 
 # symlink .dotfiles bin to ~
-ln -s $HOME/.dotfiles/bin $HOME/bin
+#ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlink for $HOME/bin folder created"
 
 # symlink .dotfiles tmux to ~
-ln -s $HOME/.dotfiles/tmux $HOME/.tmux
+ln -s $HOME/.dotfiles/tmux $HOME/.tmux && success "symlink for $HOME/.tmux folder created"
+
+# symlink VSCode User Settings
+if [ -d $HOME/Library/Application\ Support/Code/User ] ; then
+  ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
+  success "symlink for vs code settings created"
+else
+  info "symlink for vs code settings not created"
+  echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
+fi
+
+# install Source Code Pro nerd font
+cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
+success "Source Code Pro font copied successfully!"
+
+# .config permissions fix
+sudo chown $(whoami) $HOME/.config
+success '.config permissions fixed'
+
+# airport symlink
+if ! [ -f /usr/local/bin/airport ]
+  then
+    sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport
+    success "symlink for airport created"
+  else
+    info "symlink for airport already exists"
+  fi
+
+# crontab additions
+#add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+#  if [[ $? -eq 0 ]]
+#  then
+#  success "$PATH added to crontab"
+#  else
+#  info "ERROR $PATH could not be added to crontab"
+#  fi
+
+#add_cron "speedtest-cli --simple > ~/bin/bandwidth.log"
+#  if [[ $? -eq 0 ]]
+#  then
+#  success "crontab created for speedtest cli --simple"
+#  else
+#  info "ERROR crontab could not be created for speedtest cli --simple"
+#  fi
+
+#add_cron "speedtest-cli --json > ~/bin/bandwidth.json"
+#  if [[ $? -eq 0 ]]
+#  then
+#  success "crontab created for speedtest cli --json"
+#  else
+#  info "ERROR crontab could not be created for speedtest cli --json"
+#  fi
+
+# first run of speedtest-cli
+#echo "Running speedtest-cli for tmux status bar data now..."
+#speedtest-cli --simple > ~/bin/bandwidth.log
+#success "speedtest-cli bandwidth.log created"
+
+#speedtest-cli --json > ~/bin/bandwidth.json
+#success "speedtest-cli bandwidth.json created"
+
+# iterm2 config
+echo ''
+read -p "Do you currently use iTerm2 and would you like to set bechelani's custom colors? y/n" -n 1 -r
+echo ''
+if [[ $REPLY =~ ^[Yy]$ ]]
+then
+	# Specify the preferences directory
+  defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
+  # Tell iTerm2 to use the custom preferences in the directory
+  defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
+  if [[ $? -eq 0 ]]
+  then
+      success "successfully configured iTerm2 to use bechelani's custom colors..."
+  else
+      fail "failed to apply bechelani's custom colors..." >&2
+  fi
+else
+    echo "You chose not to use iTerm2 or bechelani's custom colors."
+fi
 
 echo ''
-echo '  All installed!'
+echo '  Badass macOS terminal installed!'
